export const ErrorCode = {
  // General & Client Errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',

  // Auth & Identity Errors
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',
  ACCOUNT_PENDING: 'ACCOUNT_PENDING',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_REUSED: 'AUTH_TOKEN_REUSED',
  AUTH_SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_ACCOUNT_DELETED: 'AUTH_ACCOUNT_DELETED',
  AUTH_ACCOUNT_PENDING: 'AUTH_ACCOUNT_PENDING',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_MFA_REQUIRED: 'AUTH_MFA_REQUIRED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  ADMIN_UNAUTHORIZED: 'ADMIN_UNAUTHORIZED',
  ADMIN_FORBIDDEN: 'ADMIN_FORBIDDEN',

  // Character Engine Domain Errors (Phase 3)
  CHARACTER_NOT_FOUND: 'CHARACTER_NOT_FOUND',
  CHARACTER_VERSION_NOT_FOUND: 'CHARACTER_VERSION_NOT_FOUND',
  CHARACTER_SLUG_EXISTS: 'CHARACTER_SLUG_EXISTS',
  CHARACTER_VERSION_IMMUTABLE: 'CHARACTER_VERSION_IMMUTABLE',
  CHARACTER_INVALID_CONFIG: 'CHARACTER_INVALID_CONFIG',
  CHARACTER_ALREADY_PUBLISHED: 'CHARACTER_ALREADY_PUBLISHED',
  CHARACTER_CANNOT_UNPUBLISH: 'CHARACTER_CANNOT_UNPUBLISH',
  CHARACTER_ROLLBACK_FAILED: 'CHARACTER_ROLLBACK_FAILED',
  CHARACTER_VALIDATION_FAILED: 'CHARACTER_VALIDATION_FAILED',

  // Conversation & Streaming Engine Errors (Phase 4)
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  CONVERSATION_ACCESS_DENIED: 'CONVERSATION_ACCESS_DENIED',
  CONVERSATION_LOCKED: 'CONVERSATION_LOCKED',
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  MESSAGE_INVALID: 'MESSAGE_INVALID',
  GENERATION_ALREADY_RUNNING: 'GENERATION_ALREADY_RUNNING',
  GENERATION_TIMEOUT: 'GENERATION_TIMEOUT',
  GENERATION_CANCELLED: 'GENERATION_CANCELLED',
  AI_PROVIDER_UNAVAILABLE: 'AI_PROVIDER_UNAVAILABLE',
  AI_GENERATION_FAILED: 'AI_GENERATION_FAILED',
  STREAM_INTERRUPTED: 'STREAM_INTERRUPTED',
  CONTENT_MODERATION_BLOCKED: 'CONTENT_MODERATION_BLOCKED',
  INSUFFICIENT_CREDITS: 'INSUFFICIENT_CREDITS',
  CONTENT_POLICY_VIOLATION: 'CONTENT_POLICY_VIOLATION',

  // Memory & Context Intelligence Engine Errors (Phase 5)
  MEMORY_NOT_FOUND: 'MEMORY_NOT_FOUND',
  MEMORY_DISABLED: 'MEMORY_DISABLED',
  MEMORY_ACCESS_DENIED: 'MEMORY_ACCESS_DENIED',
  MEMORY_EXTRACTION_FAILED: 'MEMORY_EXTRACTION_FAILED',
  MEMORY_EMBEDDING_FAILED: 'MEMORY_EMBEDDING_FAILED',
  MEMORY_LIMIT_EXCEEDED: 'MEMORY_LIMIT_EXCEEDED',
  MEMORY_INJECTION_DETECTED: 'MEMORY_INJECTION_DETECTED',
  MEMORY_SENSITIVE_REJECTED: 'MEMORY_SENSITIVE_REJECTED',

  // Relationship & Emotional State Engine Errors (Phase 6)
  RELATIONSHIP_NOT_FOUND: 'RELATIONSHIP_NOT_FOUND',
  RELATIONSHIP_DISABLED: 'RELATIONSHIP_DISABLED',
  RELATIONSHIP_ACCESS_DENIED: 'RELATIONSHIP_ACCESS_DENIED',
  RELATIONSHIP_RESET_FAILED: 'RELATIONSHIP_RESET_FAILED',
  RELATIONSHIP_ANALYSIS_FAILED: 'RELATIONSHIP_ANALYSIS_FAILED',
  RELATIONSHIP_STATE_CONFLICT: 'RELATIONSHIP_STATE_CONFLICT',

  // Proactive AI & Notification Intelligence Errors (Phase 7)
  PROACTIVITY_DISABLED: 'PROACTIVITY_DISABLED',
  PROACTIVITY_RATE_LIMITED: 'PROACTIVITY_RATE_LIMITED',
  QUIET_HOURS_ACTIVE: 'QUIET_HOURS_ACTIVE',
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  INVALID_PUSH_TOKEN: 'INVALID_PUSH_TOKEN',
  REMINDER_NOT_FOUND: 'REMINDER_NOT_FOUND',
  PROACTIVITY_SIMULATION_FAILED: 'PROACTIVITY_SIMULATION_FAILED',

  // AI Quality, Routing, Reliability & Evaluation Errors (Phase 8)
  AI_PROVIDER_TIMEOUT: 'AI_PROVIDER_TIMEOUT',
  AI_PROVIDER_RATE_LIMIT: 'AI_PROVIDER_RATE_LIMIT',
  AI_PROVIDER_AUTH_ERROR: 'AI_PROVIDER_AUTH_ERROR',
  AI_CONTEXT_TOO_LARGE: 'AI_CONTEXT_TOO_LARGE',
  AI_INVALID_RESPONSE: 'AI_INVALID_RESPONSE',
  AI_SAFETY_BLOCK: 'AI_SAFETY_BLOCK',
  AI_ROUTING_FAILURE: 'AI_ROUTING_FAILURE',
  AI_BUDGET_EXCEEDED: 'AI_BUDGET_EXCEEDED',
  AI_CIRCUIT_OPEN: 'AI_CIRCUIT_OPEN',
  MODEL_NOT_FOUND: 'MODEL_NOT_FOUND',
  MODEL_DISABLED: 'MODEL_DISABLED',
  MODEL_CAPABILITY_UNSUPPORTED: 'MODEL_CAPABILITY_UNSUPPORTED',
  PROMPT_NOT_FOUND: 'PROMPT_NOT_FOUND',
  PROMPT_VERSION_NOT_FOUND: 'PROMPT_VERSION_NOT_FOUND',
  PROMPT_IMMUTABLE: 'PROMPT_IMMUTABLE',
  EVALUATION_FAILED: 'EVALUATION_FAILED',
  EVALUATION_DATASET_NOT_FOUND: 'EVALUATION_DATASET_NOT_FOUND',
  EVALUATION_RUN_NOT_FOUND: 'EVALUATION_RUN_NOT_FOUND',
  REPLAY_NOT_FOUND: 'REPLAY_NOT_FOUND',

  // Voice Conversation & Real-Time Audio Errors (Phase 9)
  VOICE_PERMISSION_DENIED: 'VOICE_PERMISSION_DENIED',
  VOICE_SESSION_EXPIRED: 'VOICE_SESSION_EXPIRED',
  VOICE_SESSION_NOT_FOUND: 'VOICE_SESSION_NOT_FOUND',
  VOICE_PROVIDER_UNAVAILABLE: 'VOICE_PROVIDER_UNAVAILABLE',
  VOICE_STT_FAILED: 'VOICE_STT_FAILED',
  VOICE_TTS_FAILED: 'VOICE_TTS_FAILED',
  VOICE_CONNECTION_FAILED: 'VOICE_CONNECTION_FAILED',
  VOICE_INTERRUPTED: 'VOICE_INTERRUPTED',
  VOICE_UNSUPPORTED_LANGUAGE: 'VOICE_UNSUPPORTED_LANGUAGE',
  VOICE_UNSUPPORTED_CHARACTER: 'VOICE_UNSUPPORTED_CHARACTER',
  VOICE_USAGE_LIMIT: 'VOICE_USAGE_LIMIT',
  VOICE_ALREADY_ACTIVE: 'VOICE_ALREADY_ACTIVE',
  VOICE_DISABLED: 'VOICE_DISABLED',
  VOICE_INVALID_PACKET: 'VOICE_INVALID_PACKET',
  VOICE_AUTH_FAILED: 'VOICE_AUTH_FAILED',

  // Billing, Subscriptions, Credits & Entitlements Errors (Phase 11)
  BILLING_PROVIDER_UNAVAILABLE: 'BILLING_PROVIDER_UNAVAILABLE',
  PURCHASE_VERIFICATION_FAILED: 'PURCHASE_VERIFICATION_FAILED',
  PURCHASE_ALREADY_PROCESSED: 'PURCHASE_ALREADY_PROCESSED',
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  SUBSCRIPTION_CHANGE_NOT_ALLOWED: 'SUBSCRIPTION_CHANGE_NOT_ALLOWED',
  SUBSCRIPTION_ALREADY_ACTIVE: 'SUBSCRIPTION_ALREADY_ACTIVE',
  ENTITLEMENT_REQUIRED: 'ENTITLEMENT_REQUIRED',
  USAGE_LIMIT_REACHED: 'USAGE_LIMIT_REACHED',
  CREDIT_BALANCE_INSUFFICIENT: 'CREDIT_BALANCE_INSUFFICIENT',
  PROMOTION_NOT_ELIGIBLE: 'PROMOTION_NOT_ELIGIBLE',
  PROMOTION_EXPIRED: 'PROMOTION_EXPIRED',
  RESTORE_FAILED: 'RESTORE_FAILED',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  IDEMPOTENCY_KEY_MISSING: 'IDEMPOTENCY_KEY_MISSING',
  INVALID_PRICE: 'INVALID_PRICE',
  PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRICE_NOT_FOUND: 'PRICE_NOT_FOUND',
  WEBHOOK_VERIFICATION_FAILED: 'WEBHOOK_VERIFICATION_FAILED',
  REFUND_NOT_ALLOWED: 'REFUND_NOT_ALLOWED',

  // AI & Infrastructure Errors
  AI_PROVIDER_ERROR: 'AI_PROVIDER_ERROR',
  AI_ROUTING_FAILED: 'AI_ROUTING_FAILED',
  AI_TIMEOUT: 'AI_TIMEOUT',
  DEPENDENCY_ERROR: 'DEPENDENCY_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  REDIS_ERROR: 'REDIS_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // Phase 23 Agent & Tool Orchestration Errors
  AGENT_TASK_NOT_FOUND: 'AGENT_TASK_NOT_FOUND',
  AGENT_TASK_EXPIRED: 'AGENT_TASK_EXPIRED',
  AGENT_TASK_INVALID_STATE: 'AGENT_TASK_INVALID_STATE',
  AGENT_BUDGET_EXCEEDED: 'AGENT_BUDGET_EXCEEDED',
  AGENT_EXECUTION_FAILED: 'AGENT_EXECUTION_FAILED',
  TOOL_NOT_FOUND: 'TOOL_NOT_FOUND',
  TOOL_DISABLED: 'TOOL_DISABLED',
  TOOL_NOT_PERMITTED: 'TOOL_NOT_PERMITTED',
  TOOL_TIMEOUT: 'TOOL_TIMEOUT',
  TOOL_RATE_LIMITED: 'TOOL_RATE_LIMITED',
  TOOL_EXECUTION_FAILED: 'TOOL_EXECUTION_FAILED',
  CONSENT_REQUIRED: 'CONSENT_REQUIRED',
  CONSENT_REVOKED: 'CONSENT_REVOKED',
  CONFIRMATION_REQUIRED: 'CONFIRMATION_REQUIRED',
  CONFIRMATION_EXPIRED: 'CONFIRMATION_EXPIRED',
  CONFIRMATION_TOKEN_INVALID: 'CONFIRMATION_TOKEN_INVALID',
  CAPABILITY_DISABLED: 'CAPABILITY_DISABLED',
  SKILL_NOT_FOUND: 'SKILL_NOT_FOUND',
  SKILL_DISABLED: 'SKILL_DISABLED',
  SSRF_ATTEMPT_DETECTED: 'SSRF_ATTEMPT_DETECTED',
  PROMPT_INJECTION_DETECTED: 'PROMPT_INJECTION_DETECTED',
  EXTERNAL_ACTION_FAILED: 'EXTERNAL_ACTION_FAILED',
  OAUTH_SCOPE_MISMATCH: 'OAUTH_SCOPE_MISMATCH',
  OAUTH_TOKEN_EXPIRED: 'OAUTH_TOKEN_EXPIRED',
  MULTIMODAL_PROCESSING_FAILED: 'MULTIMODAL_PROCESSING_FAILED',
  MULTIMODAL_SIZE_EXCEEDED: 'MULTIMODAL_SIZE_EXCEEDED',
  DOCUMENT_MALWARE_DETECTED: 'DOCUMENT_MALWARE_DETECTED',

  // Phase 24 Advanced Social & Communication Layer Errors
  SOCIAL_USER_NOT_FOUND: 'SOCIAL_USER_NOT_FOUND',
  SOCIAL_USERNAME_TAKEN: 'SOCIAL_USERNAME_TAKEN',
  SOCIAL_USERNAME_INVALID: 'SOCIAL_USERNAME_INVALID',
  SOCIAL_USERNAME_RESERVED: 'SOCIAL_USERNAME_RESERVED',
  SOCIAL_BLOCKED_ACTION: 'SOCIAL_BLOCKED_ACTION',
  SOCIAL_MUTED_ACTION: 'SOCIAL_MUTED_ACTION',
  SOCIAL_ALREADY_FOLLOWING: 'SOCIAL_ALREADY_FOLLOWING',
  SOCIAL_NOT_FOLLOWING: 'SOCIAL_NOT_FOLLOWING',
  SOCIAL_CANNOT_FOLLOW_SELF: 'SOCIAL_CANNOT_FOLLOW_SELF',
  SOCIAL_CONTENT_NOT_FOUND: 'SOCIAL_CONTENT_NOT_FOUND',
  SOCIAL_CONTENT_MODERATED: 'SOCIAL_CONTENT_MODERATED',
  SOCIAL_CONTENT_REVOKED: 'SOCIAL_CONTENT_REVOKED',
  SOCIAL_COMMENT_NOT_FOUND: 'SOCIAL_COMMENT_NOT_FOUND',
  SOCIAL_COMMENT_TOO_LONG: 'SOCIAL_COMMENT_TOO_LONG',
  SOCIAL_MESSAGE_REQUEST_PENDING: 'SOCIAL_MESSAGE_REQUEST_PENDING',
  SOCIAL_MESSAGE_NOT_PERMITTED: 'SOCIAL_MESSAGE_NOT_PERMITTED',
  SOCIAL_COMMUNITY_NOT_FOUND: 'SOCIAL_COMMUNITY_NOT_FOUND',
  SOCIAL_COMMUNITY_BANNED: 'SOCIAL_COMMUNITY_BANNED',
  SOCIAL_COMMUNITY_PRIVATE: 'SOCIAL_COMMUNITY_PRIVATE',
  SOCIAL_RATE_LIMITED: 'SOCIAL_RATE_LIMITED',
  SOCIAL_AI_ACTION_DISALLOWED: 'SOCIAL_AI_ACTION_DISALLOWED',
  SOCIAL_SHARE_EXPIRED: 'SOCIAL_SHARE_EXPIRED',
  SOCIAL_PII_DETECTED: 'SOCIAL_PII_DETECTED',
  SOCIAL_FEATURE_DISABLED: 'SOCIAL_FEATURE_DISABLED',
  PAYMENT_TOOL_DISABLED: 'PAYMENT_TOOL_DISABLED',
  TOOL_PROVIDER_NOT_CONFIGURED: 'TOOL_PROVIDER_NOT_CONFIGURED',
  SOCIAL_PRIVACY_RESTRICTED: 'SOCIAL_PRIVACY_RESTRICTED',
  SOCIAL_CONFIRMATION_REQUIRED: 'SOCIAL_CONFIRMATION_REQUIRED',
  SOCIAL_CONTENT_REJECTED: 'SOCIAL_CONTENT_REJECTED',
  SOCIAL_USERNAME_COOLDOWN: 'SOCIAL_USERNAME_COOLDOWN',
  SOCIAL_PROFILE_REQUIRED: 'SOCIAL_PROFILE_REQUIRED',
  SOCIAL_NOT_ELIGIBLE: 'SOCIAL_NOT_ELIGIBLE',
  SOCIAL_IDEMPOTENCY_KEY_REQUIRED: 'SOCIAL_IDEMPOTENCY_KEY_REQUIRED',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];

export const AI_ERROR_CODES = {
  PROVIDER_TIMEOUT: ErrorCode.AI_PROVIDER_TIMEOUT,
  PROVIDER_RATE_LIMIT: ErrorCode.AI_PROVIDER_RATE_LIMIT,
  PROVIDER_AUTH_ERROR: ErrorCode.AI_PROVIDER_AUTH_ERROR,
  CONTEXT_TOO_LARGE: ErrorCode.AI_CONTEXT_TOO_LARGE,
  INVALID_RESPONSE: ErrorCode.AI_INVALID_RESPONSE,
  SAFETY_BLOCK: ErrorCode.AI_SAFETY_BLOCK,
  ROUTING_FAILURE: ErrorCode.AI_ROUTING_FAILURE,
  BUDGET_EXCEEDED: ErrorCode.AI_BUDGET_EXCEEDED,
  CIRCUIT_OPEN: ErrorCode.AI_CIRCUIT_OPEN,
  PROVIDER_UNAVAILABLE: ErrorCode.AI_PROVIDER_UNAVAILABLE,
  GENERATION_CANCELLED: ErrorCode.GENERATION_CANCELLED,
  VOICE_STT_FAILED: ErrorCode.VOICE_STT_FAILED,
  VOICE_TTS_FAILED: ErrorCode.VOICE_TTS_FAILED,
  VOICE_SESSION_EXPIRED: ErrorCode.VOICE_SESSION_EXPIRED,
} as const;

export const SYSTEM_CONSTANTS = {
  PAGINATION: {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 20,
    MAX_LIMIT: 100,
  },
  MEMORY: {
    MAX_RETRIEVED_MEMORIES: 6,
    MIN_SIMILARITY_THRESHOLD: 0.60,
    MAX_PROMPT_MEMORY_TOKENS: 800,
    RECENCY_DECAY_LAMBDA: 0.0231, // 30-day half-life: ln(2) / 30 ~ 0.0231
    DUPLICATE_COSINE_THRESHOLD: 0.88,
    CONFLICT_COSINE_THRESHOLD: 0.82,
    EXTRACTION_MIN_CONFIDENCE: 0.50,
    EXTRACTION_MIN_IMPORTANCE: 0.30,
    SUMMARIZATION_MESSAGE_THRESHOLD: 20,
    SUMMARIZATION_CHUNK_SIZE: 15,
    RETRIEVAL_TIMEOUT_MS: 500,
    WEIGHTS: {
      SIMILARITY: 0.45,
      IMPORTANCE: 0.20,
      RECENCY: 0.15,
      CONFIDENCE: 0.10,
      REINFORCEMENT: 0.10,
    },
  },
  RELATIONSHIP: {
    DIMENSION_BOUNDS: {
      MIN: 0,
      MAX: 100,
    },
    INITIAL_DIMENSIONS: {
      FAMILIARITY: 0,
      TRUST: 20,
      COMFORT: 20,
      AFFECTION: 10,
      ENGAGEMENT: 50,
    },
    STAGE_THRESHOLDS: {
      STRANGER: { minFamiliarity: 0, minTrust: 0, minComfort: 0, minAffection: 0 },
      ACQUAINTANCE: { minFamiliarity: 20, minTrust: 20, minComfort: 15, minAffection: 0 },
      FRIEND: { minFamiliarity: 40, minTrust: 40, minComfort: 35, minAffection: 15 },
      CLOSE_FRIEND: { minFamiliarity: 60, minTrust: 60, minComfort: 55, minAffection: 30 },
      CONFIDANT: { minFamiliarity: 75, minTrust: 75, minComfort: 70, minAffection: 50 },
      ROMANTIC_PARTNER: { minFamiliarity: 85, minTrust: 85, minComfort: 80, minAffection: 80 },
    },
    DECAY_RATES: {
      FAMILIARITY_MONTHLY: 0.01, // 1% per 30 days
      ENGAGEMENT_DAILY: 0.05, // 5% per inactive day after 7 days
      TRUST_DAILY: 0.0, // Stable
    },
    DIMINISHING_RETURNS_FACTOR: 0.2,
    CACHE_TTL_SECONDS: 600, // 10 minutes
    EMOTIONAL_STATE_TTL_SECONDS: 7200, // 2 hours
  },
  CHAT: {
    MAX_MESSAGE_LENGTH: 4000,
    SHORT_TERM_CONTEXT_LIMIT: 20,
    CONTEXT_WINDOW_TOKEN_BUDGET: 8000,
    STREAM_TIMEOUT_MS: 45000,
    FIRST_TOKEN_TIMEOUT_MS: 15000,
    TOTAL_GENERATION_TIMEOUT_MS: 120000,
    CONVERSATION_LOCK_TTL_SECONDS: 60,
    HEARTBEAT_INTERVAL_MS: 15000,
  },
  AUTH: {
    ACCESS_TOKEN_LIFETIME_SECONDS: 900, // 15 mins
    REFRESH_TOKEN_LIFETIME_SECONDS: 2592000, // 30 days
    EMAIL_VERIFICATION_TOKEN_LIFETIME_SECONDS: 86400, // 24 hours
    PASSWORD_RESET_TOKEN_LIFETIME_SECONDS: 3600, // 1 hour
    MIN_PASSWORD_LENGTH: 8,
    MAX_PASSWORD_LENGTH: 128,
  },
  SECURITY: {
    ARGON2_MEMORY_COST: 65536, // 64 MB
    ARGON2_TIME_COST: 3,
    ARGON2_PARALLELISM: 4,
  },
  CACHE: {
    CHARACTER_TTL_SECONDS: 3600, // 1 hour
    CHARACTER_VERSION_TTL_SECONDS: 86400, // 24 hours
    USER_MEMORY_SETTINGS_TTL_SECONDS: 300, // 5 mins
    USER_RELATIONSHIP_TTL_SECONDS: 600, // 10 mins
    USER_NOTIFICATIONS_TTL_SECONDS: 300, // 5 mins
    USER_ENTITLEMENTS_TTL_SECONDS: 300, // 5 mins (Phase 11)
  },
  PROACTIVITY: {
    DEFAULT_QUIET_HOURS_START: '22:30',
    DEFAULT_QUIET_HOURS_END: '08:00',
    DEFAULT_MAX_DAILY_NOTIFICATIONS: 3,
    DEFAULT_MAX_WEEKLY_NOTIFICATIONS: 14,
    MIN_COOLDOWN_HOURS: 6,
    IGNORED_NOTIFICATION_COOLDOWN_HOURS: 24,
    DISENGAGED_COOLDOWN_HOURS: 72,
    RECENT_INTERACTION_BUFFER_MINUTES: 10,
    SIMILARITY_REJECTION_THRESHOLD: 0.82,
    INTENT_DEFAULT_EXPIRY_HOURS: 12,
    SCANNER_BATCH_SIZE: 100,
    DISTRIBUTED_LOCK_TTL_MS: 30000,
    TOKEN_BUDGET_PROACTIVE: 3000,
  },
  AI_QUALITY: {
    DEFAULT_PRICING: {
      MOCK: { inputPer1k: 0.0001, outputPer1k: 0.0002 },
      GPT_4O_MINI: { inputPer1k: 0.00015, outputPer1k: 0.0006 },
      GPT_4O: { inputPer1k: 0.005, outputPer1k: 0.015 },
      CLAUDE_3_5_SONNET: { inputPer1k: 0.003, outputPer1k: 0.015 },
      CLAUDE_3_5_HAIKU: { inputPer1k: 0.0008, outputPer1k: 0.004 },
      TEXT_EMBEDDING_3_SMALL: { inputPer1k: 0.00002, outputPer1k: 0.0 },
    },
    CIRCUIT_BREAKER: {
      FAILURE_RATE_THRESHOLD: 0.5, // Trip when 50% fail
      MIN_REQUESTS_SAMPLE: 10,
      COOLDOWN_SECONDS: 30,
      HALF_OPEN_SUCCESS_REQUIRED: 3,
    },
    RETRY: {
      MAX_ATTEMPTS: 3,
      INITIAL_BACKOFF_MS: 300,
      MAX_BACKOFF_MS: 2000,
      BACKOFF_FACTOR: 2,
    },
    CONTEXT_BUDGET: {
      DEFAULT_MAX_TOKENS: 8000,
      RESERVE_OUTPUT_TOKENS: 800,
      SAFETY_TIER_WEIGHTS: {
        SYSTEM_SAFETY: 1.0,
        RUNTIME_CONSTRAINTS: 0.95,
        USER_MESSAGE: 0.90,
        CHARACTER_IDENTITY: 0.85,
        CURRENT_CONVERSATION: 0.70,
        RELEVANT_MEMORY: 0.55,
        RELATIONSHIP_CONTEXT: 0.40,
        OPTIONAL_HISTORY: 0.20,
      },
    },
    EVALUATION: {
      MIN_PASS_COMPOSITE_SCORE: 0.75,
      REGRESSION_TOLERANCE_DELTA: -0.05,
      CRITERIA_WEIGHTS: {
        RELEVANCE: 0.25,
        CHARACTER_CONSISTENCY: 0.25,
        MEMORY_GROUNDING: 0.20,
        SAFETY: 0.20,
        NATURALNESS: 0.10,
      },
    },
  },
  VOICE: {
    DEFAULT_SAMPLE_RATE: 24000,
    DEFAULT_CHANNELS: 1,
    DEFAULT_ENCODING: 'pcm16',
    FRAME_DURATION_MS: 20,
    CHUNK_SIZE_BYTES: 960,
    MAX_SESSION_DURATION_SECONDS: 1800,
    SESSION_LOCK_TTL_SECONDS: 60,
    HEARTBEAT_INTERVAL_MS: 10000,
    CLIENT_TIMEOUT_MS: 30000,
    VAD_SILENCE_THRESHOLD_MS: 800,
    VAD_MIN_SPEECH_DURATION_MS: 300,
    MAX_QUEUED_TTS_CHUNKS: 50,
    SENTENCE_DELIMITERS_REGEX: /[.!?;\n]+|(?<=[,])\s+/g,
    PRICING: {
      STT_PER_MINUTE_USD: {
        OPENAI_WHISPER: 0.006,
        DEEPGRAM_NOVA: 0.0043,
        MOCK: 0.001,
      },
      TTS_PER_1K_CHARS_USD: {
        ELEVENLABS_TURBO: 0.015,
        OPENAI_TTS_1: 0.015,
        OPENAI_TTS_1_HD: 0.030,
        MOCK: 0.001,
      },
    },
  },
  BILLING: {
    SUPPORTED_CURRENCIES: ['INR', 'USD', 'EUR', 'GBP'] as const,
    DEFAULT_CURRENCY: 'USD',
    USAGE_RESERVATION_TTL_SECONDS: 300, // 5 minutes
    GRACE_PERIOD_DAYS: 3,
    MAX_WEBHOOK_RETRIES: 5,
    WEBHOOK_RETRY_BACKOFF_MS: 1000,
    METER_UNITS: {
      AI_TEXT_TOKENS: 'ai_text_tokens',
      VOICE_SECONDS: 'voice_seconds',
      IMAGE_GENERATIONS: 'image_generations',
      PREMIUM_MESSAGES: 'premium_messages',
      PROACTIVE_MESSAGES: 'proactive_messages',
    },
    DEFAULT_FREE_LIMITS: {
      AI_TEXT_TOKENS: 50000,
      VOICE_SECONDS: 120, // 2 minutes
      IMAGE_GENERATIONS: 5,
    },
    ENTITLEMENT_KEYS: {
      CHAT_BASIC: 'chat_basic',
      CHAT_PRIORITY: 'chat_priority',
      PREMIUM_CHARACTERS: 'premium_characters',
      VOICE_ACCESS: 'voice_access',
      IMAGE_GENERATION: 'image_generation',
      ADVANCED_MEMORY: 'advanced_memory',
      PROACTIVE_MESSAGES: 'proactive_messages',
      HIGHER_CONTEXT: 'higher_context',
      PREMIUM_MODELS: 'premium_models',
      AD_FREE: 'ad_free',
      CUSTOM_PERSONALITY: 'custom_personality',
      CUSTOM_VOICE: 'custom_voice',
    },
  },
} as const;

export const ADMIN_PERMISSIONS = {
  USERS_READ: 'users.read',
  USERS_WRITE: 'users.write',
  USERS_SUSPEND: 'users.suspend',
  USERS_DELETE: 'users.delete',
  CHARACTERS_READ: 'characters.read',
  CHARACTERS_WRITE: 'characters.write',
  CHARACTERS_CREATE: 'characters.create',
  CHARACTERS_UPDATE: 'characters.update',
  CHARACTERS_PUBLISH: 'characters.publish',
  CHARACTERS_ROLLBACK: 'characters.rollback',
  CHARACTERS_ARCHIVE: 'characters.archive',
  CHARACTERS_TEST: 'characters.test',
  CHARACTERS_DEBUG: 'characters.debug',
  CHARACTERS_KNOWLEDGE_READ: 'characters.knowledge.read',
  CHARACTERS_KNOWLEDGE_WRITE: 'characters.knowledge.write',
  CHARACTERS_SAFETY_READ: 'characters.safety.read',
  CHARACTERS_SAFETY_WRITE: 'characters.safety.write',
  MEMORIES_READ: 'memories.read',
  MEMORIES_WRITE: 'memories.write',
  MEMORIES_DEBUG: 'memories.debug',
  MEMORIES_DELETE: 'memories.delete',
  RELATIONSHIPS_READ: 'relationships.read',
  RELATIONSHIPS_WRITE: 'relationships.write',
  RELATIONSHIPS_DEBUG: 'relationships.debug',
  RELATIONSHIPS_RESET: 'relationships.reset',
  PROACTIVITY_READ: 'proactivity.read',
  PROACTIVITY_WRITE: 'proactivity.write',
  PROACTIVITY_DEBUG: 'proactivity.debug',
  NOTIFICATIONS_READ: 'notifications.read',
  NOTIFICATIONS_WRITE: 'notifications.write',
  AI_READ: 'ai.read',
  AI_MODELS_READ: 'ai.models.read',
  AI_MODELS_WRITE: 'ai.models.write',
  AI_PROMPTS_READ: 'ai.prompts.read',
  AI_PROMPTS_WRITE: 'ai.prompts.write',
  AI_PLAYGROUND: 'ai.playground',
  AI_EVALUATE: 'ai.evaluate',
  AI_PRODUCTION_REPLAY: 'ai.production_replay',
  AI_COST_READ: 'ai.cost.read',
  AI_AUDIT_READ: 'ai.audit.read',
  VOICE_READ: 'voice.read',
  VOICE_WRITE: 'voice.write',
  VOICE_PREVIEW: 'voice.preview',
  VOICE_COST_READ: 'voice.cost.read',
  VOICE_TELEMETRY_READ: 'voice.telemetry.read',
  CONTENT_READ: 'content.read',
  CONTENT_WRITE: 'content.write',
  ANALYTICS_READ: 'analytics.read',
  BILLING_READ: 'billing.read',
  BILLING_WRITE: 'billing.write',
  BILLING_PLANS_READ: 'billing.plans.read',
  BILLING_PLANS_WRITE: 'billing.plans.write',
  BILLING_SUBSCRIPTIONS_READ: 'billing.subscriptions.read',
  BILLING_REFUNDS_WRITE: 'billing.refunds.write',
  BILLING_PROMOTIONS_WRITE: 'billing.promotions.write',
  BILLING_RECONCILIATION_WRITE: 'billing.reconciliation.write',
  BILLING_WEBHOOKS_READ: 'billing.webhooks.read',
  BILLING_WEBHOOKS_RETRY: 'billing.webhooks.retry',
  BILLING_CREDITS_GRANT: 'billing.credits.grant',
  BILLING_AUDIT_READ: 'billing.audit.read',
  MODERATION_READ: 'moderation.read',
  MODERATION_WRITE: 'moderation.write',
  SETTINGS_READ: 'settings.read',
  SETTINGS_WRITE: 'settings.write',
  FEATURE_FLAGS_READ: 'feature_flags.read',
  FEATURE_FLAGS_WRITE: 'feature_flags.write',
  AUDIT_LOGS_READ: 'audit_logs.read',
  SUPPORT_READ: 'support.read',
  SUPPORT_WRITE: 'support.write',
  INCIDENTS_READ: 'incidents.read',
  INCIDENTS_WRITE: 'incidents.write',
  KILL_SWITCHES_WRITE: 'kill_switches.write',
  BETA_WRITE: 'beta.write',
  APPROVALS_WRITE: 'approvals.write',
  INTELLIGENCE_READ: 'intelligence.read',
  INTELLIGENCE_WRITE: 'intelligence.write',
  INTELLIGENCE_REPLAY: 'intelligence.replay',
  CIRCUIT_BREAKER_OVERRIDE: 'circuit_breaker.override',
  AGENTS_READ: 'agents.read',
  AGENTS_WRITE: 'agents.write',
  AGENTS_PLAYGROUND: 'agents.playground',
  TOOLS_READ: 'tools.read',
  TOOLS_WRITE: 'tools.write',
  SKILLS_READ: 'skills.read',
  SKILLS_WRITE: 'skills.write',
  CAPABILITIES_READ: 'capabilities.read',
  CAPABILITIES_WRITE: 'capabilities.write',
  OAUTH_CONNECTORS_READ: 'oauth_connectors.read',
  OAUTH_CONNECTORS_WRITE: 'oauth_connectors.write',
  HIGH_RISK_OVERRIDE: 'high_risk.override',

  // Phase 24 Social Admin Permissions
  SOCIAL_READ: 'social.read',
  SOCIAL_WRITE: 'social.write',
  SOCIAL_MODERATE: 'social.moderate',
  COMMUNITIES_MODERATE: 'communities.moderate',
  SOCIAL_CONFIG_WRITE: 'social.config.write',
  SOCIAL_KILL_SWITCH_WRITE: 'social.kill_switch.write',
  /** Break-glass access to private direct-message content. Granted to no role except super_admin; every use is audited with a purpose. */
  SOCIAL_PRIVATE_CONTENT_READ: 'social.private_content.read',
  /** Character simulation operations (runs, replay, version migration). */
  SIMULATION_READ: 'simulation.read',
  SIMULATION_OPERATE: 'simulation.operate',
  /** Developer-platform oversight: projects, key metadata, webhooks; and suspending a project. */
  DEVELOPER_PLATFORM_READ: 'developer_platform.read',
  DEVELOPER_PLATFORM_WRITE: 'developer_platform.write',
} as const;

export type AdminPermissionType = (typeof ADMIN_PERMISSIONS)[keyof typeof ADMIN_PERMISSIONS];

export const ADMIN_ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  SUPPORT: 'support',
  CONTENT_MANAGER: 'content_manager',
  ANALYST: 'analyst',
  MODERATOR: 'moderator',
} as const;

export type AdminRoleType = (typeof ADMIN_ROLES)[keyof typeof ADMIN_ROLES];

export const DEFAULT_ROLE_PERMISSIONS: Record<AdminRoleType, readonly AdminPermissionType[]> = {
  super_admin: Object.values(ADMIN_PERMISSIONS),
  admin: [
    ADMIN_PERMISSIONS.USERS_READ,
    ADMIN_PERMISSIONS.USERS_WRITE,
    ADMIN_PERMISSIONS.USERS_SUSPEND,
    ADMIN_PERMISSIONS.CHARACTERS_READ,
    ADMIN_PERMISSIONS.CHARACTERS_WRITE,
    ADMIN_PERMISSIONS.CHARACTERS_CREATE,
    ADMIN_PERMISSIONS.CHARACTERS_UPDATE,
    ADMIN_PERMISSIONS.CHARACTERS_PUBLISH,
    ADMIN_PERMISSIONS.CHARACTERS_ROLLBACK,
    ADMIN_PERMISSIONS.CHARACTERS_ARCHIVE,
    ADMIN_PERMISSIONS.CHARACTERS_TEST,
    ADMIN_PERMISSIONS.CHARACTERS_DEBUG,
    ADMIN_PERMISSIONS.CHARACTERS_KNOWLEDGE_READ,
    ADMIN_PERMISSIONS.CHARACTERS_KNOWLEDGE_WRITE,
    ADMIN_PERMISSIONS.CHARACTERS_SAFETY_READ,
    ADMIN_PERMISSIONS.CHARACTERS_SAFETY_WRITE,
    ADMIN_PERMISSIONS.MEMORIES_READ,
    ADMIN_PERMISSIONS.MEMORIES_WRITE,
    ADMIN_PERMISSIONS.MEMORIES_DEBUG,
    ADMIN_PERMISSIONS.MEMORIES_DELETE,
    ADMIN_PERMISSIONS.RELATIONSHIPS_READ,
    ADMIN_PERMISSIONS.RELATIONSHIPS_WRITE,
    ADMIN_PERMISSIONS.RELATIONSHIPS_DEBUG,
    ADMIN_PERMISSIONS.RELATIONSHIPS_RESET,
    ADMIN_PERMISSIONS.PROACTIVITY_READ,
    ADMIN_PERMISSIONS.PROACTIVITY_WRITE,
    ADMIN_PERMISSIONS.PROACTIVITY_DEBUG,
    ADMIN_PERMISSIONS.NOTIFICATIONS_READ,
    ADMIN_PERMISSIONS.NOTIFICATIONS_WRITE,
    ADMIN_PERMISSIONS.AI_READ,
    ADMIN_PERMISSIONS.AI_MODELS_READ,
    ADMIN_PERMISSIONS.AI_MODELS_WRITE,
    ADMIN_PERMISSIONS.AI_PROMPTS_READ,
    ADMIN_PERMISSIONS.AI_PROMPTS_WRITE,
    ADMIN_PERMISSIONS.AI_PLAYGROUND,
    ADMIN_PERMISSIONS.AI_EVALUATE,
    ADMIN_PERMISSIONS.AI_PRODUCTION_REPLAY,
    ADMIN_PERMISSIONS.AI_COST_READ,
    ADMIN_PERMISSIONS.AI_AUDIT_READ,
    ADMIN_PERMISSIONS.VOICE_READ,
    ADMIN_PERMISSIONS.VOICE_WRITE,
    ADMIN_PERMISSIONS.VOICE_PREVIEW,
    ADMIN_PERMISSIONS.VOICE_COST_READ,
    ADMIN_PERMISSIONS.VOICE_TELEMETRY_READ,
    ADMIN_PERMISSIONS.CONTENT_READ,
    ADMIN_PERMISSIONS.CONTENT_WRITE,
    ADMIN_PERMISSIONS.ANALYTICS_READ,
    ADMIN_PERMISSIONS.BILLING_READ,
    ADMIN_PERMISSIONS.BILLING_WRITE,
    ADMIN_PERMISSIONS.BILLING_PLANS_READ,
    ADMIN_PERMISSIONS.BILLING_PLANS_WRITE,
    ADMIN_PERMISSIONS.BILLING_SUBSCRIPTIONS_READ,
    ADMIN_PERMISSIONS.BILLING_REFUNDS_WRITE,
    ADMIN_PERMISSIONS.BILLING_PROMOTIONS_WRITE,
    ADMIN_PERMISSIONS.BILLING_RECONCILIATION_WRITE,
    ADMIN_PERMISSIONS.BILLING_WEBHOOKS_READ,
    ADMIN_PERMISSIONS.BILLING_WEBHOOKS_RETRY,
    ADMIN_PERMISSIONS.BILLING_CREDITS_GRANT,
    ADMIN_PERMISSIONS.BILLING_AUDIT_READ,
    ADMIN_PERMISSIONS.MODERATION_READ,
    ADMIN_PERMISSIONS.MODERATION_WRITE,
    ADMIN_PERMISSIONS.SETTINGS_READ,
    ADMIN_PERMISSIONS.FEATURE_FLAGS_READ,
    ADMIN_PERMISSIONS.AUDIT_LOGS_READ,
    ADMIN_PERMISSIONS.SUPPORT_READ,
    ADMIN_PERMISSIONS.SUPPORT_WRITE,
    ADMIN_PERMISSIONS.INCIDENTS_READ,
    ADMIN_PERMISSIONS.INCIDENTS_WRITE,
    ADMIN_PERMISSIONS.KILL_SWITCHES_WRITE,
    ADMIN_PERMISSIONS.BETA_WRITE,
    ADMIN_PERMISSIONS.INTELLIGENCE_READ,
    ADMIN_PERMISSIONS.INTELLIGENCE_WRITE,
    ADMIN_PERMISSIONS.INTELLIGENCE_REPLAY,
    ADMIN_PERMISSIONS.AGENTS_READ,
    ADMIN_PERMISSIONS.AGENTS_WRITE,
    ADMIN_PERMISSIONS.AGENTS_PLAYGROUND,
    ADMIN_PERMISSIONS.TOOLS_READ,
    ADMIN_PERMISSIONS.TOOLS_WRITE,
    ADMIN_PERMISSIONS.SKILLS_READ,
    ADMIN_PERMISSIONS.SKILLS_WRITE,
    ADMIN_PERMISSIONS.CAPABILITIES_READ,
    ADMIN_PERMISSIONS.CAPABILITIES_WRITE,
    ADMIN_PERMISSIONS.OAUTH_CONNECTORS_READ,
    ADMIN_PERMISSIONS.OAUTH_CONNECTORS_WRITE,
    ADMIN_PERMISSIONS.SOCIAL_READ,
    ADMIN_PERMISSIONS.SOCIAL_WRITE,
    ADMIN_PERMISSIONS.SOCIAL_MODERATE,
    ADMIN_PERMISSIONS.COMMUNITIES_MODERATE,
    ADMIN_PERMISSIONS.SOCIAL_CONFIG_WRITE,
    ADMIN_PERMISSIONS.SOCIAL_KILL_SWITCH_WRITE,
    ADMIN_PERMISSIONS.SIMULATION_READ,
    ADMIN_PERMISSIONS.SIMULATION_OPERATE,
    ADMIN_PERMISSIONS.DEVELOPER_PLATFORM_READ,
    ADMIN_PERMISSIONS.DEVELOPER_PLATFORM_WRITE,
  ],
  support: [
    ADMIN_PERMISSIONS.USERS_READ,
    ADMIN_PERMISSIONS.USERS_SUSPEND,
    ADMIN_PERMISSIONS.MODERATION_READ,
    ADMIN_PERMISSIONS.AUDIT_LOGS_READ,
    ADMIN_PERMISSIONS.RELATIONSHIPS_READ,
    ADMIN_PERMISSIONS.PROACTIVITY_READ,
    ADMIN_PERMISSIONS.NOTIFICATIONS_READ,
    ADMIN_PERMISSIONS.VOICE_READ,
    ADMIN_PERMISSIONS.BILLING_READ,
    ADMIN_PERMISSIONS.BILLING_SUBSCRIPTIONS_READ,
    ADMIN_PERMISSIONS.SUPPORT_READ,
    ADMIN_PERMISSIONS.SUPPORT_WRITE,
    ADMIN_PERMISSIONS.INCIDENTS_READ,
    ADMIN_PERMISSIONS.AGENTS_READ,
    ADMIN_PERMISSIONS.SOCIAL_READ,
  ],
  content_manager: [
    ADMIN_PERMISSIONS.CHARACTERS_READ,
    ADMIN_PERMISSIONS.CHARACTERS_WRITE,
    ADMIN_PERMISSIONS.CHARACTERS_CREATE,
    ADMIN_PERMISSIONS.CHARACTERS_UPDATE,
    ADMIN_PERMISSIONS.CHARACTERS_PUBLISH,
    ADMIN_PERMISSIONS.CHARACTERS_ROLLBACK,
    ADMIN_PERMISSIONS.CHARACTERS_TEST,
    ADMIN_PERMISSIONS.CHARACTERS_KNOWLEDGE_READ,
    ADMIN_PERMISSIONS.CHARACTERS_KNOWLEDGE_WRITE,
    ADMIN_PERMISSIONS.CHARACTERS_SAFETY_READ,
    ADMIN_PERMISSIONS.VOICE_READ,
    ADMIN_PERMISSIONS.VOICE_PREVIEW,
    ADMIN_PERMISSIONS.CONTENT_READ,
    ADMIN_PERMISSIONS.CONTENT_WRITE,
    ADMIN_PERMISSIONS.RELATIONSHIPS_READ,
    ADMIN_PERMISSIONS.RELATIONSHIPS_DEBUG,
    ADMIN_PERMISSIONS.PROACTIVITY_READ,
    ADMIN_PERMISSIONS.PROACTIVITY_DEBUG,
    ADMIN_PERMISSIONS.CAPABILITIES_READ,
    ADMIN_PERMISSIONS.CAPABILITIES_WRITE,
    ADMIN_PERMISSIONS.SKILLS_READ,
  ],
  analyst: [
    ADMIN_PERMISSIONS.USERS_READ,
    ADMIN_PERMISSIONS.CHARACTERS_READ,
    ADMIN_PERMISSIONS.ANALYTICS_READ,
    ADMIN_PERMISSIONS.INTELLIGENCE_READ,
    ADMIN_PERMISSIONS.BILLING_READ,
    ADMIN_PERMISSIONS.BILLING_SUBSCRIPTIONS_READ,
    ADMIN_PERMISSIONS.BILLING_PLANS_READ,
    ADMIN_PERMISSIONS.RELATIONSHIPS_READ,
    ADMIN_PERMISSIONS.PROACTIVITY_READ,
    ADMIN_PERMISSIONS.SUPPORT_READ,
    ADMIN_PERMISSIONS.INCIDENTS_READ,
    ADMIN_PERMISSIONS.AGENTS_READ,
    ADMIN_PERMISSIONS.SOCIAL_READ,
  ],
  moderator: [
    ADMIN_PERMISSIONS.USERS_READ,
    ADMIN_PERMISSIONS.USERS_SUSPEND,
    ADMIN_PERMISSIONS.CHARACTERS_READ,
    ADMIN_PERMISSIONS.MODERATION_READ,
    ADMIN_PERMISSIONS.MODERATION_WRITE,
    ADMIN_PERMISSIONS.AUDIT_LOGS_READ,
    ADMIN_PERMISSIONS.RELATIONSHIPS_READ,
    ADMIN_PERMISSIONS.SUPPORT_READ,
    ADMIN_PERMISSIONS.AGENTS_READ,
    ADMIN_PERMISSIONS.SOCIAL_READ,
    ADMIN_PERMISSIONS.SOCIAL_MODERATE,
    ADMIN_PERMISSIONS.COMMUNITIES_MODERATE,
  ],
};

export const FEATURE_FLAGS = {
  ENABLE_MEMORY_EXTRACTION: 'ENABLE_MEMORY_EXTRACTION',
  ENABLE_PROACTIVE_MESSAGING: 'ENABLE_PROACTIVE_MESSAGING',
  ENABLE_VOICE_CALLS: 'ENABLE_VOICE_CALLS',
  ENABLE_IMAGE_GENERATION: 'ENABLE_IMAGE_GENERATION',
  ENABLE_GIFTS: 'ENABLE_GIFTS',
  ENABLE_BILLING: 'ENABLE_BILLING',
  ENABLE_MOBILE_PURCHASES: 'ENABLE_MOBILE_PURCHASES',
  ENABLE_WEB_CHECKOUT: 'ENABLE_WEB_CHECKOUT',
  ENABLE_CREDITS: 'ENABLE_CREDITS',
  ENABLE_VOICE_PAID_USAGE: 'ENABLE_VOICE_PAID_USAGE',
  ENABLE_IMAGE_PAID_USAGE: 'ENABLE_IMAGE_PAID_USAGE',
  ENABLE_PAYWALL_V2: 'ENABLE_PAYWALL_V2',
  ENABLE_MAINTENANCE_MODE: 'ENABLE_MAINTENANCE_MODE',
  ENABLE_BETA_PROGRAM: 'ENABLE_BETA_PROGRAM',
  ENABLE_STATUS_PAGE_METRICS: 'ENABLE_STATUS_PAGE_METRICS',
  ENABLE_PERSONALIZATION_ENGINE: 'ENABLE_PERSONALIZATION_ENGINE',
  ENABLE_AI_COST_CIRCUIT_BREAKER: 'ENABLE_AI_COST_CIRCUIT_BREAKER',
  ENABLE_AI_QUALITY_CIRCUIT_BREAKER: 'ENABLE_AI_QUALITY_CIRCUIT_BREAKER',
  ENABLE_SHADOW_MODEL_ROUTING: 'ENABLE_SHADOW_MODEL_ROUTING',
  ENABLE_AGENT_RUNTIME: 'ENABLE_AGENT_RUNTIME',
  ENABLE_EXTERNAL_TOOLS: 'ENABLE_EXTERNAL_TOOLS',
  ENABLE_SECURE_BROWSER: 'ENABLE_SECURE_BROWSER',
  ENABLE_OAUTH_CONNECTORS: 'ENABLE_OAUTH_CONNECTORS',
  ENABLE_HIGH_RISK_ACTIONS: 'ENABLE_HIGH_RISK_ACTIONS',
  ENABLE_MULTIMODAL_PROCESSING: 'ENABLE_MULTIMODAL_PROCESSING',
  ENABLE_CREATOR_TOOLS: 'ENABLE_CREATOR_TOOLS',
  ENABLE_SCHEDULED_AGENTS: 'ENABLE_SCHEDULED_AGENTS',
  ENABLE_AGENT_SOCIAL_ACTIONS: 'ENABLE_AGENT_SOCIAL_ACTIONS',

  // Phase 24 Social Feature Flags
  ENABLE_SOCIAL_IDENTITY: 'ENABLE_SOCIAL_IDENTITY',
  ENABLE_SOCIAL_FEED: 'ENABLE_SOCIAL_FEED',
  ENABLE_USER_FOLLOWING: 'ENABLE_USER_FOLLOWING',
  ENABLE_CHARACTER_FOLLOWING: 'ENABLE_CHARACTER_FOLLOWING',
  ENABLE_CHARACTER_SHARING: 'ENABLE_CHARACTER_SHARING',
  ENABLE_CONVERSATION_SHARING: 'ENABLE_CONVERSATION_SHARING',
  ENABLE_CONTENT_REACTIONS: 'ENABLE_CONTENT_REACTIONS',
  ENABLE_COMMENTS: 'ENABLE_COMMENTS',
  ENABLE_USER_MESSAGING: 'ENABLE_USER_MESSAGING',
  ENABLE_MESSAGE_REQUESTS: 'ENABLE_MESSAGE_REQUESTS',
  ENABLE_COMMUNITIES: 'ENABLE_COMMUNITIES',
  ENABLE_AI_SOCIAL_ACTIONS: 'ENABLE_AI_SOCIAL_ACTIONS',
  ENABLE_SOCIAL_RECOMMENDATIONS: 'ENABLE_SOCIAL_RECOMMENDATIONS',
  // Per-feature rollout and kill switches for the social layer live in the versioned
  // social policy (see DEFAULT_SOCIAL_POLICY / SocialPolicyService), not in these keys.
} as const;

export const INTELLIGENCE_CONSTANTS = {
  PERSONALIZATION: {
    DEFAULT_DECAY_HALF_LIFE_DAYS: 14,
    MIN_CONFIDENCE_THRESHOLD: 0.6,
    MAX_INFERRED_PREFERENCES_IN_CONTEXT: 5,
    MAX_TOKEN_BUDGET: 400,
  },
  CIRCUIT_BREAKERS: {
    DAILY_COST_LIMIT_USD: 500.0,
    QUALITY_MIN_COMPOSITE_SCORE: 0.7,
    SAFETY_INCIDENT_MAX_PER_HOUR: 5,
    COOLDOWN_MS: 300000, // 5 minutes
  },
  DATASET: {
    DEFAULT_VERSION: 'evaluation_dataset_v1',
    MAX_FAILURE_CASES_PER_CATEGORY: 500,
  },
} as const;

export const AGENT_CONSTANTS = {
  DEFAULT_BOUNDS: {
    MAX_STEPS: 8,
    MAX_TOOL_CALLS: 12,
    MAX_DURATION_MS: 120000, // 2 minutes
    MAX_TOKENS: 16000,
    MAX_COST_USD: 0.25,
    MAX_RETRIES: 2,
    MAX_PARALLEL_TOOLS: 3,
    DEFAULT_TIMEOUT_MS: 30000,
  },
  SSRF_BLOCKLIST_PATTERNS: [
    '127.0.0.1',
    'localhost',
    '0.0.0.0',
    '169.254.169.254',
    '::1',
    '10.',
    '192.168.',
    '172.16.',
    '172.17.',
    '172.18.',
    '172.19.',
    '172.20.',
    '172.21.',
    '172.22.',
    '172.23.',
    '172.24.',
    '172.25.',
    '172.26.',
    '172.27.',
    '172.28.',
    '172.29.',
    '172.30.',
    '172.31.',
  ],
  MAX_TOOL_OUTPUT_BYTES: 32768, // 32KB
  MAX_MULTIMODAL_FILE_SIZE_BYTES: 15728640, // 15MB
  CONFIRMATION_TOKEN_TTL_MS: 600000, // 10 minutes
} as const;

/**
 * Phase 24 social layer.
 *
 * Every social primitive is an independent feature with its own rollout and its own kill switch.
 * `DEFAULT_SOCIAL_POLICY` is the seed for the versioned `SocialPolicyVersion` table; the admin
 * Social Studio edits a copy of it and every change produces a new, auditable, rollback-able version.
 */
export const SOCIAL_FEATURES = [
  'social_identity',
  'user_following',
  'character_following',
  'character_sharing',
  'public_conversation_sharing',
  'reactions',
  'comments',
  'mentions',
  'messaging',
  'message_requests',
  'communities',
  'creator_communities',
  'social_feed',
  'social_recommendations',
  'social_search',
  'social_notifications',
  'ai_social_posts',
  'character_social_actions',
] as const;

export type SocialFeatureKey = (typeof SOCIAL_FEATURES)[number];

export type SocialRolloutCohort = 'internal' | 'creator_beta' | 'general';

export interface SocialFeatureRollout {
  enabled: boolean;
  /** 0-100, deterministic per user bucket. */
  rolloutPercent: number;
  /** Cohorts that always receive the feature when enabled (e.g. internal staff, creator beta). */
  cohorts: SocialRolloutCohort[];
  platforms?: Array<'ios' | 'android' | 'web'>;
  minAppVersion?: string;
  deniedRegions?: string[];
}

export interface SocialRateLimitRule {
  limit: number;
  windowSeconds: number;
}

export type SocialRateLimitedAction =
  | 'follow'
  | 'unfollow'
  | 'block'
  | 'mute'
  | 'reaction'
  | 'comment'
  | 'share'
  | 'report'
  | 'message_send'
  | 'message_request'
  | 'community_create'
  | 'community_join'
  | 'content_publish'
  | 'ai_social_action'
  | 'username_change'
  | 'profile_read'
  | 'share_read';

export interface SocialPolicyConfig {
  features: Record<SocialFeatureKey, SocialFeatureRollout>;
  /** Independent emergency switches. `true` = feature forcibly disabled regardless of rollout. */
  killSwitches: Record<SocialFeatureKey, boolean>;
  rateLimits: Record<SocialRateLimitedAction, SocialRateLimitRule>;
  username: { changeCooldownDays: number; releaseHoldDays: number };
  sharing: {
    defaultExpiryDays: number;
    maxExcerptMessages: number;
    /** What happens when high-risk PII is detected: BLOCK refuses; REDACT_AND_CONFIRM redacts and requires explicit confirmation. */
    highRiskPiiAction: 'BLOCK' | 'REDACT_AND_CONFIRM';
    requirePreModeration: boolean;
  };
  comments: { maxLength: number; maxThreadDepth: 1; editWindowMinutes: number; maxMentions: number; maxLinks: number };
  messaging: {
    maxLength: number;
    requestExpiryDays: number;
    dailyRequestLimit: number;
    maxPendingOutgoingRequests: number;
    maxMessagesBeforeAccept: number;
    maxAttachmentBytes: number;
    allowedAttachmentMimeTypes: string[];
  };
  communities: {
    minAccountAgeDays: number;
    requireVerifiedCreator: boolean;
    maxOwnedCommunities: number;
    maxMembersDefault: number;
  };
  notifications: { aggregationWindowSeconds: number; maxSocialPerRecipientPerDay: number; fanoutBatchSize: number };
  feed: {
    pageSize: number;
    maxRecencyDays: number;
    maxItemsPerAuthorPerPage: number;
    fatigueHalfLifeHours: number;
    candidateCacheSeconds: number;
  };
  aiSocial: {
    maxPostsPerDayPlatformCap: number;
    maxRepliesPerHourPlatformCap: number;
    globalDailyBudgetCents: number;
    perCreatorDailyBudgetCents: number;
    minScheduleIntervalHours: number;
  };
  moderation: {
    autoHideReportThreshold: number;
    /** Report count alone never actions content; auto-hide additionally needs a matching automated signal. */
    autoHideRequiresAutomatedSignal: boolean;
    appealWindowDays: number;
  };
  abuse: {
    newAccountAgeHours: number;
    newAccountRateMultiplier: number;
    followCycleThreshold: number;
    duplicateContentWindowSeconds: number;
  };
}

const featureOn = (rolloutPercent: number, cohorts: SocialRolloutCohort[] = ['internal']): SocialFeatureRollout => ({
  enabled: true,
  rolloutPercent,
  cohorts,
});

const featureOff = (): SocialFeatureRollout => ({ enabled: false, rolloutPercent: 0, cohorts: ['internal'] });

export const DEFAULT_SOCIAL_POLICY: SocialPolicyConfig = {
  features: {
    social_identity: featureOn(100),
    user_following: featureOn(100),
    character_following: featureOn(100),
    character_sharing: featureOn(100),
    public_conversation_sharing: featureOn(0, ['internal', 'creator_beta']),
    reactions: featureOn(100),
    comments: featureOn(100),
    mentions: featureOn(100),
    messaging: featureOn(0, ['internal']),
    message_requests: featureOn(0, ['internal']),
    communities: featureOn(0, ['internal', 'creator_beta']),
    creator_communities: featureOn(0, ['internal', 'creator_beta']),
    social_feed: featureOn(100),
    social_recommendations: featureOn(100),
    social_search: featureOn(100),
    social_notifications: featureOn(100),
    ai_social_posts: featureOff(),
    character_social_actions: featureOff(),
  },
  killSwitches: {
    social_identity: false,
    user_following: false,
    character_following: false,
    character_sharing: false,
    public_conversation_sharing: false,
    reactions: false,
    comments: false,
    mentions: false,
    messaging: false,
    message_requests: false,
    communities: false,
    creator_communities: false,
    social_feed: false,
    social_recommendations: false,
    social_search: false,
    social_notifications: false,
    ai_social_posts: false,
    character_social_actions: false,
  },
  rateLimits: {
    follow: { limit: 60, windowSeconds: 3600 },
    unfollow: { limit: 60, windowSeconds: 3600 },
    block: { limit: 50, windowSeconds: 3600 },
    mute: { limit: 100, windowSeconds: 3600 },
    reaction: { limit: 300, windowSeconds: 3600 },
    comment: { limit: 30, windowSeconds: 3600 },
    share: { limit: 20, windowSeconds: 3600 },
    report: { limit: 20, windowSeconds: 3600 },
    message_send: { limit: 120, windowSeconds: 3600 },
    message_request: { limit: 20, windowSeconds: 86400 },
    community_create: { limit: 2, windowSeconds: 86400 },
    community_join: { limit: 30, windowSeconds: 3600 },
    content_publish: { limit: 10, windowSeconds: 3600 },
    ai_social_action: { limit: 20, windowSeconds: 3600 },
    username_change: { limit: 5, windowSeconds: 86400 },
    profile_read: { limit: 600, windowSeconds: 3600 },
    share_read: { limit: 300, windowSeconds: 3600 },
  },
  username: { changeCooldownDays: 14, releaseHoldDays: 30 },
  sharing: {
    defaultExpiryDays: 90,
    maxExcerptMessages: 20,
    highRiskPiiAction: 'REDACT_AND_CONFIRM',
    requirePreModeration: true,
  },
  comments: { maxLength: 1000, maxThreadDepth: 1, editWindowMinutes: 15, maxMentions: 5, maxLinks: 2 },
  messaging: {
    maxLength: 2000,
    requestExpiryDays: 14,
    dailyRequestLimit: 20,
    maxPendingOutgoingRequests: 25,
    maxMessagesBeforeAccept: 1,
    maxAttachmentBytes: 10 * 1024 * 1024,
    allowedAttachmentMimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
  },
  communities: {
    minAccountAgeDays: 14,
    requireVerifiedCreator: true,
    maxOwnedCommunities: 3,
    maxMembersDefault: 5000,
  },
  notifications: { aggregationWindowSeconds: 300, maxSocialPerRecipientPerDay: 30, fanoutBatchSize: 500 },
  feed: {
    pageSize: 20,
    maxRecencyDays: 14,
    maxItemsPerAuthorPerPage: 3,
    fatigueHalfLifeHours: 48,
    candidateCacheSeconds: 60,
  },
  aiSocial: {
    maxPostsPerDayPlatformCap: 5,
    maxRepliesPerHourPlatformCap: 10,
    globalDailyBudgetCents: 50_000,
    perCreatorDailyBudgetCents: 500,
    minScheduleIntervalHours: 24,
  },
  moderation: { autoHideReportThreshold: 5, autoHideRequiresAutomatedSignal: true, appealWindowDays: 30 },
  abuse: {
    newAccountAgeHours: 72,
    newAccountRateMultiplier: 0.25,
    followCycleThreshold: 5,
    duplicateContentWindowSeconds: 600,
  },
};

export const SOCIAL_CONSTANTS = {
  USERNAME: {
    MIN_LENGTH: 3,
    MAX_LENGTH: 30,
    /** Applied after NFKC normalization + lowercasing. ASCII only: blocks mixed-script lookalikes outright. */
    REGEX: /^[a-z0-9](?:[a-z0-9_.]*[a-z0-9])?$/,
    RESERVED: [
      'admin', 'administrator', 'system', 'root', 'support', 'official', 'ai_companion', 'moderator', 'mod',
      'help', 'helpdesk', 'safety', 'security', 'trust', 'api', 'staff', 'team', 'platform', 'verified',
      'billing', 'payments', 'legal', 'privacy', 'abuse', 'report', 'null', 'undefined', 'anonymous',
      'deleted', 'everyone', 'here', 'me', 'settings', 'share', 'u', 'c', 'p', 'community',
    ],
    /** Substrings that imply platform authority; blocked anywhere in the canonical form. */
    RESERVED_SUBSTRINGS: ['admin', 'moderator', 'official', 'support', 'staff', 'aicompanion'],
  },
  PUBLIC_ID_BYTES: 16,
  REPORT_REASONS: [
    'SPAM',
    'HARASSMENT',
    'HATE',
    'SEXUAL_CONTENT',
    'MINOR_SAFETY',
    'VIOLENCE',
    'SELF_HARM',
    'IMPERSONATION',
    'SCAM',
    'PRIVACY_VIOLATION',
    'INTELLECTUAL_PROPERTY',
    'MISLEADING_AI_CONTENT',
    'OTHER',
  ],
  CONSENT_TYPES: [
    'DIRECT_MESSAGING',
    'CREATOR_COMMUNICATION',
    'CHARACTER_PROACTIVE_SOCIAL',
    'COMMUNITY_PARTICIPATION',
    'EXTERNAL_SHARING',
    'SOCIAL_NOTIFICATIONS',
    'AI_GENERATED_PUBLIC_CONTENT',
  ],
  CONSENT_POLICY_VERSION: '2026.09',
} as const;


